### ISSUE TITLE
`import qdyn` does not import modules

### ISSUE THREAD

**Issue by ablech** [qucontrol/qdynpylib#14]
* qdynpylib version: 0.4.0
* Python version: 7.3.7
* Operating System: Ubuntu 18.04

### Description

If I install the qdynpylib by `make develop` or `make install` and want to use the package in a jupyter notebook or with IPython, the `import qdyn` command does not import the individual modules.

See e.g. the output of the following commands:
```python
In [1]: import qdyn 
In [2]: dir(qdyn)                                                                                                                     
Out[2]: 
['__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__']
```

If I then try to access a certain module, e.g. `qdyn.config`, this raises an `AttributeError`:
```python
In [3]: dir(qdyn.config)                                                                                                              
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-39234df004b3> in <module>
----> 1 dir(qdyn.config)

AttributeError: module 'qdyn' has no attribute 'config'
```
However, the module can be accessed, if it is imported individually:
```python
In [4]: import qdyn.config                                                                                                            

In [5]: dir(qdyn)                                                                                                                     
Out[5]: 
['__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 'config',
 'units']
```

Is this the intended behaviour?

**Comment by goerz** [comment]
Yeah, I think I originally chose not to expose sub-packages because the sub-packages were all very disjunct, and I didn't yet have a fully formed opinion on the best practices with respect to exposing sub-packages automatically. Generally speaking, Python packages don't *have to* expose their sub-packages. Most notably, `scipy` doesn't do this: `import scipy` will not make `scipy.optimize` available - you have to do `import scipy.optimize` explicitly to get it. My current opinion on this is that in general, every Python package should directly expose all its sub-packages, except for if importing a sub-package has undesired side-effects (which is a bad design), or the import is unusually slow (which can happen if there are complex decorators or other dynamic code generators). It's also OK not to expose submodules that aren't really part of the public API (sub-packages containing internal testing code, for example, although a better design is to make these private by prepending _ to the package name). I don't think QDYN-pylib has any of those caveats, so I'm in favor of changing the current behavior.

All that needs to happen is that `src/qdyn/__init__.py` has to contain lines like
~~~
from . import config
~~~
for all sub-packages (see the `__init__.py` in the `krotov` package as an example).

**Comment by ablech** [comment]
Thank you for the explanation, I'm still learning a lot about package managing...

I agree with you to expose the submodules, in particular since the top-level module does not provide functionality.
